FROM centos:8
# 地域設定
RUN yum install -y langpacks-ja
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

# 環境構築
RUN yum update -y && \
    yum install -y tree vim wget openssl-devel epel-release openssh-server passwd
# ansibleを動かすためにpythonインストール
RUN dnf install -y python3 && \
    alternatives --set python /usr/bin/python3
## rootパスワードを設定
RUN echo "password" | passwd --stdin root
EXPOSE 50122
CMD /sbin/init
