FROM centos:8
# 環境設定
RUN sed -i -e '/override_install_langs/s/$/,ja_JP.utf8/g' /etc/yum.conf && \
    yum -y install --enablerepo=base glibc-common                       && \
    yum clean all                                                       && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

# 環境構築
RUN yum update -y && \
    yum install -y tree vim wget openssl-devel epel-release openssh-server
## rootパスワードを設定
RUN echo "password" | passwd --stdin root
EXPOSE 50021
CMD /sbin/init
