FROM ubuntu:20.04
# 環境設定
RUN apt update -y
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

# 環境構築
RUN apt update -y && \
    apt install -y tree vim wget openssl openssh-server iproute2 sudo
#RUN apt install -y git
## rootパスワードを設定
RUN echo 'root:password' | chpasswd
## ssh接続設定
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 50022
CMD /sbin/init

# https://qiita.com/kuboshu83/items/f827ad7068550cded72d