FROM centos:7
# locale
RUN sed -i -e '/override_install_langs/s/$/,ja_JP.utf8/g' /etc/yum.conf && \
    yum -y install --enablerepo=base glibc-common                       && \
    yum clean all                                                       && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8   \
    LANGUAGE=ja_JP:ja  \
    LC_ALL=ja_JP.UTF-8 \
    TZ=Asia/Tokyo

## rootパスワードを設定
RUN echo "password" | passwd --stdin root

# 環境構築
RUN yum update -y && \
    yum install -y tree vim wget openssl-devel epel-release openssh-server

EXPOSE 50121
CMD /sbin/init
