- hosts: centos
  become: yes
  vars:
    python_url: https://www.python.org/ftp/python/3.5.9/Python-3.5.9.tar.xz
    dest_dir: /home/ec2-user/tmp/
  tasks:
    - name: yumのアップデート
      yum:
        name=*
        state=latest
      register: result_update
    - debug: msg={{result_update}}
    - name: epelのインストール
      yum: 
        name: 
          - epel-release
          - xrdp
          - tigervnc-server
        state: installed
      when:
         ansible_distribution == "CentOS"
    - name: 開発ツールのインストール
      yum:
        name: 
          - tree
          - vim
          - wget
          - openssl-devel
          - httpd
          - mysql
        state: installed
      register: result_install
    - debug: msg={{result_install}}

    - name: installing python
      get_url:
        url={{python_url}}
        dest={{dest_dir}}
      register: result
    - name: extracting python_file
      unarchive: 
        src="{{dest_dir}}Python-3.5.9.tar.xz"
        dest={{dest_dir}}
      register: result
    - name: shellの実行
      shell: ./configure --prefix=/usr/local/python
      args:
        chdir: ~/tmp/Python-3.5.9        
    - debug: msg={{result}}